### ISSUE TITLE
how to make it run in HA OS?

### ISSUE THREAD

**Issue by neilbacon** [kubaceg/sofar_g3_lsw3_logger_reader#11]
Hi, built OK, but how do I add this to my HA OS? Where do I put the executable and how do I make it run? I see there are lots of other projects doing similar things for different data loggers, so I guess everyone but me knows what to do.

**Comment by kubaceg** [comment]
I created a simple plugin that is responsible for running this logger reader. It's not public ready but I think it's time to finish and release it :) I'll try to do it by the end of july :)
In the meanwhile just put binary build for appropriate architecture on your HA machine, create `sofar.yaml` config file on the same directory, and run it by hand using e.g. `Terminal` plugin for HA.

The only required dependency is MQTT broker e.g. mosquito MQTT.

Hope it helps. Please as If You have more questions.
I'll be back with plugin :)

**Comment by neilbacon** [comment]
Thanks for your response. It's a few years since I've used home assistant and I had to get back up to speed. I have your code running on another machine and connecting to the lsw3 logger on port 8899 and HA MQTT just fine now.

I notice very useful scale factors and units in adapters/devices/sofar/sofar_protocol.go. If the code used HA MQTT "discovery" this useful info would be available in HA wouldn't it? 

Comparing the output with the Solarman app, these seem to be the real-time fields of interest (power is in units of 10W):
 
**ActivePower_Output_Total = 442**
Total PV generation

**Power_PV1 = 230, Power_PV2 = 228**
PV output of string 1 and string 2.
My strings point in the same direction with same number of panels, so a significant difference might indicate a shading problem.
Sum is 3.5% < ActivePower_Output_Total (inverter inefficiency?)

**ActivePower_Load_Sys = 362** 
total power consumption

**ActivePower_PCC_Total = 80**
grid export (+) or import (-) = ActivePower_Output_Total - ActivePower_Load_Sys (so it is redundant data)

My inverter is: SOFAR 5KTLM-G3-A and I don't have a battery, so maybe data is slightly different from yours. These keys are in the code but missing from the MQTT topic sensors/energy/inverter/All:
"GridOutput_Rsvd1"
"GridOutput_Rsvd2"
"R_Rsvd1"
"R_Rsvd2"
"S_Rsvd1"
"S_Rsvd2"
"T_Rsvd1"
"T_Rsvd2"

The R, S T prefixes and suffixes are apparently for 3 phase power and the S & T values will always be zero for single phase systems.

Is fetching and messaging for all the unwanted data (lots of zeros) an overhead worth avoiding?  Worth some user config to say what they want?

**Comment by kubaceg** [comment]
Honestly I use only `PV_Generation_Today` measurement in my HA :) 

> Is fetching and messaging for all the unwanted data (lots of zeros) an overhead worth avoiding? Worth some user config to say what they want?

I had a plan to make a filter for unused metrics and send only required metrics to MQTT but I don't have time for that. All this unwanted data must be saved in HA database so I think there are some reasons to filter this out. I encourage to contributing :) Filtering would be really nice feature.

>  notice very useful scale factors and units in adapters/devices/sofar/sofar_protocol.go. If the code used HA MQTT "discovery" this useful info would be available in HA wouldn't it?

We have to send data in their most basic units because software has the possibility to convert basic units into human-readable automatically e.g. in Grafana You choose that `PV_Generation_Today` is the metric responsible for `Power (watts)`. That' why we can't use factors to convert data inside this exporter. That information is only for development. process, for example this information helps to define my sensor in HA
```  sensor:
    - name: "inverter_today_generation"
      state_topic: "/sensors/energy/inverter/PV_Generation_Today"
      device_class: energy
      state_class: measurement
      unit_of_measurement: 'kWh'
      value_template: "{{ value|int * 0.01 }}"```
