### ISSUE TITLE
Failed to perform measurements

### ISSUE THREAD

**Issue by mef123** [kubaceg/sofar_g3_lsw3_logger_reader#4]
Hello,

I'm facing issues with reader
Here is the exact error 
```
2023/02/05 20:25:01 using TCP/IP communications port 192.168.xx.xx:8899
2023/02/05 20:25:01 performing measurements
2023/02/05 20:25:01 MQTT Connected
2023/02/05 20:25:03 failed to perform measurements: short reply: 29 bytes
2023/02/05 20:25:03 performing measurements
```
I'm using Afore inverter with LSW-3 logger:
Firmware version: LSW3_15_1E03_1.31

serial is:  2327xxxxxx

Checked with nmap - port 8899 is open

Here is registry file, shared from Afore:

[AFORE_T4.pdf](https://github.com/kubaceg/sofar_g3_lsw3_logger_reader/files/10612046/AFORE_T4.pdf)

**Comment by kubaceg** [comment]
Registers are different than Sofar registers which are implemented in this solution. You can try another project like https://github.com/MichaluxPL/Sofar_LSW3 there are plenty of projects for LSW3 loggers which implement different registers.
