### ISSUE TITLE
OTLP instrumentation

### ISSUE THREAD

**Issue by brianroch** [kubaceg/sofar_g3_lsw3_logger_reader#6]
[Otel Metrics ](https://github.com/open-telemetry/opentelemetry-go#project-status) is now in Alpha release for Go. 

I think it would be beneficial to instrument this codebase so that all gathered values are captured as gauges and made available using the [OTLP exporter](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp/otlpmetric).

This is similar to @nosireland 's Solar Invertor Monitor that exports to Prometheus: https://github.com/NosIreland/solismon3

@kubaceg: I'm happy to submit the code for this. Just wanted to create an issue first to discuss whether it's something you feel belongs in this project?

**Comment by kubaceg** [comment]
Nice idea :) gathering data in Prometheus and displaying a nice dashboard in Grafana sounds exciting 🤩 

Do You plan to implement it as an additional database implementation?

**Comment by brianroch** [comment]
Yes. Pretty much how you have it implemented for MQTT at the moment. Add the OTel collector details to the config file. If they are present, then the metrics will be pushed right after they are gathered. They can be pushed via http or gRPC.

**Comment by kubaceg** [comment]
Sounds good. I think it's worth making that both databases can work at the same time.

**Comment by brianroch** [comment]
Great. I've started work on this already, so will open a PR once it's done.

Exporting the metrics via OTLP to an OTel collector should allow them to be pushed to a wide variety of platforms using the [various exporters](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter) that have been built.
